In [17]:
import pymongo
import pandas as pd
import numpy as np
import statistics
from src.personalinfo import get_user,get_password

In [18]:
user = get_user()
password = get_password()

## Reading data from database

In [19]:
client = pymongo.MongoClient(f'mongodb+srv://{user}:{password}@cluster0.uprf1q8.mongodb.net/')
db = client["Datasets"]
collection = db["CensusIncomeDataSet"]

In [20]:
allData = collection.find()

In [21]:
data = pd.DataFrame(allData)

In [22]:
data.head()

_id  age workclass  fnlwgt     education  \
0  64d4c1eae56fafdb1d98fe3b   90         ?   77053       HS-grad   
1  64d4c1eae56fafdb1d98fe3c   82   Private  132870       HS-grad   
2  64d4c1eae56fafdb1d98fe3d   66         ?  186061  Some-college   
3  64d4c1eae56fafdb1d98fe3e   54   Private  140359       7th-8th   
4  64d4c1eae56fafdb1d98fe3f   41   Private  264663  Some-college   

   education.num marital.status         occupation   relationship   race  \
0              9        Widowed                  ?  Not-in-family  White   
1              9        Widowed    Exec-managerial  Not-in-family  White   
2             10        Widowed                  ?      Unmarried  Black   
3              4       Divorced  Machine-op-inspct      Unmarried  White   
4             10      Separated     Prof-specialty      Own-child  White   

      sex  capital.gain  capital.loss  hours.per.week native.country income  
0  Female             0          4356              40  United-States  <=50K  
1  Female             0          4356              18  United-States  <=50K  
2  Female             0          4356              40  United-States  <=50K  
3  Female             0          3900              40  United-States  <=50K  
4  Female             0          3900              40  United-States  <=50K

Spliting dependent and independent features

In [23]:
X = data.iloc[:,:-1]
Y = data[['income']]

## EDA

In [24]:
X.describe()

age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours.per.week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

#### Checking datatypes

In [25]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   _id             32561 non-null  object
 1   age             32561 non-null  int64 
 2   workclass       32561 non-null  object
 3   fnlwgt          32561 non-null  int64 
 4   education       32561 non-null  object
 5   education.num   32561 non-null  int64 
 6   marital.status  32561 non-null  object
 7   occupation      32561 non-null  object
 8   relationship    32561 non-null  object
 9   race            32561 non-null  object
 10  sex             32561 non-null  object
 11  capital.gain    32561 non-null  int64 
 12  capital.loss    32561 non-null  int64 
 13  hours.per.week  32561 non-null  int64 
 14  native.country  32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


#### Checking duplicates

In [26]:
X.duplicated().sum()

0

#### Checking missing values

In [27]:
X.isnull().sum()

_id               0
age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
dtype: int64

#### We can see sum missing values with '?'

In [28]:
X.head()

_id  age workclass  fnlwgt     education  \
0  64d4c1eae56fafdb1d98fe3b   90         ?   77053       HS-grad   
1  64d4c1eae56fafdb1d98fe3c   82   Private  132870       HS-grad   
2  64d4c1eae56fafdb1d98fe3d   66         ?  186061  Some-college   
3  64d4c1eae56fafdb1d98fe3e   54   Private  140359       7th-8th   
4  64d4c1eae56fafdb1d98fe3f   41   Private  264663  Some-college   

   education.num marital.status         occupation   relationship   race  \
0              9        Widowed                  ?  Not-in-family  White   
1              9        Widowed    Exec-managerial  Not-in-family  White   
2             10        Widowed                  ?      Unmarried  Black   
3              4       Divorced  Machine-op-inspct      Unmarried  White   
4             10      Separated     Prof-specialty      Own-child  White   

      sex  capital.gain  capital.loss  hours.per.week native.country  
0  Female             0          4356              40  United-States  
1  Female             0          4356              18  United-States  
2  Female             0          4356              40  United-States  
3  Female             0          3900              40  United-States  
4  Female             0          3900              40  United-States

## `age feature`

In [29]:
X['age'].unique()

array([90, 82, 66, 54, 41, 34, 38, 74, 68, 45, 52, 32, 51, 46, 57, 22, 37,
       29, 61, 21, 33, 49, 23, 59, 60, 63, 53, 44, 43, 71, 48, 73, 67, 40,
       50, 42, 39, 55, 47, 31, 58, 62, 36, 72, 78, 83, 26, 70, 27, 35, 81,
       65, 25, 28, 56, 69, 20, 30, 24, 64, 75, 19, 77, 80, 18, 17, 76, 79,
       88, 84, 85, 86, 87], dtype=int64)

no missing values

In [30]:
(X['age'] == '?').sum()

0

checking dtypes

In [31]:
X['age'].dtypes

dtype('int64')

## `workclass feature`

In [32]:
X['workclass'].unique()

array(['?', 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [33]:
(X['workclass'] == '?').sum()

1836

handling missing values with mode

In [34]:
X['workclass'] = X['workclass'].replace('?',statistics.mode(X['workclass']))

In [35]:
(X['workclass'] == '?').sum()

0

In [36]:
X['workclass'].unique()

array(['Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

lets remove hyphen and give space instead

In [37]:
X['workclass'] = X['workclass'].str.replace('-',' ')

In [38]:
X['workclass'].unique()

array(['Private', 'State gov', 'Federal gov', 'Self emp not inc',
       'Self emp inc', 'Local gov', 'Without pay', 'Never worked'],
      dtype=object)

#### Checking dtypes

In [39]:
X['workclass'].dtypes

dtype('O')

## `fnlwgt feature`

In [40]:
X['fnlwgt'].unique()

array([ 77053, 132870, 186061, ...,  34066,  84661, 257302], dtype=int64)

In [41]:
(X['fnlwgt'] == '?').sum()

0

In [42]:
X['fnlwgt'].dtypes

dtype('int64')

## `education feature`

In [43]:
X['education'].unique()

array(['HS-grad', 'Some-college', '7th-8th', '10th', 'Doctorate',
       'Prof-school', 'Bachelors', 'Masters', '11th', 'Assoc-acdm',
       'Assoc-voc', '1st-4th', '5th-6th', '12th', '9th', 'Preschool'],
      dtype=object)

In [44]:
(X['education'] == '?').sum()

0

In [45]:
SSC_string = ['7th-8th','10th','1st-4th','5th-6th','9th']
HSC_string = ['11th','12th']

In [46]:
X['education'] = X['education'].replace(SSC_string,'ssc')
X['education'] = X['education'].replace(SSC_string,'ssc')
X['education'] = X['education'].str.replace('-',' ')

In [47]:
X['education'].unique()

array(['HS grad', 'Some college', 'ssc', 'Doctorate', 'Prof school',
       'Bachelors', 'Masters', '11th', 'Assoc acdm', 'Assoc voc', '12th',
       'Preschool'], dtype=object)

In [48]:
X.head()

_id  age workclass  fnlwgt     education  \
0  64d4c1eae56fafdb1d98fe3b   90   Private   77053       HS grad   
1  64d4c1eae56fafdb1d98fe3c   82   Private  132870       HS grad   
2  64d4c1eae56fafdb1d98fe3d   66   Private  186061  Some college   
3  64d4c1eae56fafdb1d98fe3e   54   Private  140359           ssc   
4  64d4c1eae56fafdb1d98fe3f   41   Private  264663  Some college   

   education.num marital.status         occupation   relationship   race  \
0              9        Widowed                  ?  Not-in-family  White   
1              9        Widowed    Exec-managerial  Not-in-family  White   
2             10        Widowed                  ?      Unmarried  Black   
3              4       Divorced  Machine-op-inspct      Unmarried  White   
4             10      Separated     Prof-specialty      Own-child  White   

      sex  capital.gain  capital.loss  hours.per.week native.country  
0  Female             0          4356              40  United-States  
1  Female             0          4356              18  United-States  
2  Female             0          4356              40  United-States  
3  Female             0          3900              40  United-States  
4  Female             0          3900              40  United-States

In [49]:
X['education'].dtypes

dtype('O')

## `education.num feature`

By looking we dont need education feature instead we need education.num , 
education.num gives us numbers of each education category for example doctor = 16, HS grad = 9 and so on its like encoding 

In [50]:
X['education.num'].unique()

array([ 9, 10,  4,  6, 16, 15, 13, 14,  7, 12, 11,  2,  3,  8,  5,  1],
      dtype=int64)

In [51]:
X['education.num'].dtypes

dtype('int64')

In [52]:
X['education.num'].dtypes

dtype('int64')

## `marital.status feature`

In [53]:
X['marital.status'].unique()

array(['Widowed', 'Divorced', 'Separated', 'Never-married',
       'Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [54]:
X['marital.status'] = X['marital.status'].str.replace('-',' ')

In [55]:
X['marital.status'].unique()

array(['Widowed', 'Divorced', 'Separated', 'Never married',
       'Married civ spouse', 'Married spouse absent', 'Married AF spouse'],
      dtype=object)

In [56]:
X['marital.status'].dtypes

dtype('O')

## `occupation feature`

In [57]:
X['occupation'].unique()

array(['?', 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [58]:
(X['occupation'] == '?').sum()

1843

In [59]:
X['occupation'] = X['occupation'].replace('?',statistics.mode(X['occupation']))
X['occupation'] = X['occupation'].str.replace('-',' ')

In [60]:
X['occupation'].unique()

array(['Prof specialty', 'Exec managerial', 'Machine op inspct',
       'Other service', 'Adm clerical', 'Craft repair',
       'Transport moving', 'Handlers cleaners', 'Sales',
       'Farming fishing', 'Tech support', 'Protective serv',
       'Armed Forces', 'Priv house serv'], dtype=object)

In [61]:
X['occupation'].dtypes

dtype('O')

## `relationship feature`

In [62]:
X['relationship'].unique()

array(['Not-in-family', 'Unmarried', 'Own-child', 'Other-relative',
       'Husband', 'Wife'], dtype=object)

In [63]:
X['relationship'] = X['relationship'].str.replace('-',' ')

In [64]:
X['relationship'].unique()

array(['Not in family', 'Unmarried', 'Own child', 'Other relative',
       'Husband', 'Wife'], dtype=object)

In [65]:
X['relationship'].dtypes

dtype('O')

## `race feature`

In [66]:
X['race'].unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Other',
       'Amer-Indian-Eskimo'], dtype=object)

In [67]:
X['race'] = X['race'].str.replace('-',' ')

In [68]:
X['race'].unique()

array(['White', 'Black', 'Asian Pac Islander', 'Other',
       'Amer Indian Eskimo'], dtype=object)

In [69]:
X['race'].dtypes

dtype('O')

## `sex feature`

In [70]:
X['sex'].unique()

array(['Female', 'Male'], dtype=object)

In [71]:
X['sex'].dtypes

dtype('O')

## `capital.gain feature`

In [72]:
X['capital.gain'].unique()

array([    0, 99999, 41310, 34095, 27828, 25236, 25124, 22040, 20051,
       18481, 15831, 15024, 15020, 14344, 14084, 13550, 11678, 10605,
       10566, 10520,  9562,  9386,  8614,  7978,  7896,  7688,  7443,
        7430,  7298,  6849,  6767,  6723,  6514,  6497,  6418,  6360,
        6097,  5721,  5556,  5455,  5178,  5060,  5013,  4934,  4931,
        4865,  4787,  4687,  4650,  4508,  4416,  4386,  4101,  4064,
        3942,  3908,  3887,  3818,  3781,  3674,  3471,  3464,  3456,
        3432,  3418,  3411,  3325,  3273,  3137,  3103,  2993,  2977,
        2964,  2961,  2936,  2907,  2885,  2829,  2653,  2635,  2597,
        2580,  2538,  2463,  2414,  2407,  2387,  2354,  2346,  2329,
        2290,  2228,  2202,  2176,  2174,  2105,  2062,  2050,  2036,
        2009,  1848,  1831,  1797,  1639,  1506,  1471,  1455,  1424,
        1409,  1173,  1151,  1111,  1086,  1055,   991,   914,   594,
         401,   114], dtype=int64)

In [73]:
X['capital.gain'].dtypes

dtype('int64')

## `capital.loss feature`

In [74]:
X['capital.loss'].unique()

array([4356, 3900, 3770, 3683, 3004, 2824, 2754, 2603, 2559, 2547, 2489,
       2472, 2467, 2457, 2444, 2415, 2392, 2377, 2352, 2339, 2282, 2267,
       2258, 2246, 2238, 2231, 2206, 2205, 2201, 2179, 2174, 2163, 2149,
       2129, 2080, 2057, 2051, 2042, 2002, 2001, 1980, 1977, 1974, 1944,
       1902, 1887, 1876, 1848, 1844, 1825, 1816, 1762, 1755, 1741, 1740,
       1735, 1726, 1721, 1719, 1672, 1669, 1668, 1651, 1648, 1628, 1617,
       1602, 1594, 1590, 1579, 1573, 1564, 1539, 1504, 1485, 1411, 1408,
       1380, 1340, 1258, 1138, 1092,  974,  880,  810,  653,  625,  419,
        323,  213,  155,    0], dtype=int64)

In [75]:
X['capital.loss'].dtypes

dtype('int64')

## `hours.per.week feature`

In [76]:
X['hours.per.week'].unique()

array([40, 18, 45, 20, 60, 35, 55, 76, 50, 42, 25, 32, 90, 48, 15, 70, 52,
       72, 39,  6, 65, 12, 80, 67, 99, 30, 75, 26, 36, 10, 84, 38, 62, 44,
        8, 28, 59,  5, 24, 57, 34, 37, 46, 56, 41, 98, 43, 63,  1, 47, 68,
       54,  2, 16,  9,  3,  4, 33, 23, 22, 64, 51, 19, 58, 53, 96, 66, 21,
        7, 13, 27, 11, 14, 77, 31, 78, 49, 17, 85, 87, 88, 73, 89, 97, 94,
       29, 82, 86, 91, 81, 92, 61, 74, 95], dtype=int64)

In [77]:
X['hours.per.week'].dtypes

dtype('int64')

## `native.country feature`

In [78]:
X['native.country'].unique()

array(['United-States', '?', 'Mexico', 'Greece', 'Vietnam', 'China',
       'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago', 'Canada',
       'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland', 'Iran',
       'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras', 'Cuba',
       'Ireland', 'Cambodia', 'Peru', 'Nicaragua', 'Dominican-Republic',
       'Haiti', 'El-Salvador', 'Hungary', 'Columbia', 'Guatemala',
       'Jamaica', 'Ecuador', 'France', 'Yugoslavia', 'Scotland',
       'Portugal', 'Laos', 'Thailand', 'Outlying-US(Guam-USVI-etc)'],
      dtype=object)

In [79]:
X['native.country'] = X['occupation'].replace('?',statistics.mode(X['native.country']))
X['native.country'] = X['native.country'].str.replace('-',' ')

In [80]:
X['native.country'].unique()

array(['Prof specialty', 'Exec managerial', 'Machine op inspct',
       'Other service', 'Adm clerical', 'Craft repair',
       'Transport moving', 'Handlers cleaners', 'Sales',
       'Farming fishing', 'Tech support', 'Protective serv',
       'Armed Forces', 'Priv house serv'], dtype=object)

In [81]:
X['native.country'].dtypes

dtype('O')

droping unwanted columns

In [82]:
X.head()

_id  age workclass  fnlwgt     education  \
0  64d4c1eae56fafdb1d98fe3b   90   Private   77053       HS grad   
1  64d4c1eae56fafdb1d98fe3c   82   Private  132870       HS grad   
2  64d4c1eae56fafdb1d98fe3d   66   Private  186061  Some college   
3  64d4c1eae56fafdb1d98fe3e   54   Private  140359           ssc   
4  64d4c1eae56fafdb1d98fe3f   41   Private  264663  Some college   

   education.num marital.status         occupation   relationship   race  \
0              9        Widowed     Prof specialty  Not in family  White   
1              9        Widowed    Exec managerial  Not in family  White   
2             10        Widowed     Prof specialty      Unmarried  Black   
3              4       Divorced  Machine op inspct      Unmarried  White   
4             10      Separated     Prof specialty      Own child  White   

      sex  capital.gain  capital.loss  hours.per.week     native.country  
0  Female             0          4356              40     Prof specialty  
1  Female             0          4356              18    Exec managerial  
2  Female             0          4356              40     Prof specialty  
3  Female             0          3900              40  Machine op inspct  
4  Female             0          3900              40     Prof specialty

In [83]:
X.drop(columns=['_id','education'])

age workclass  fnlwgt  education.num      marital.status  \
0       90   Private   77053              9             Widowed   
1       82   Private  132870              9             Widowed   
2       66   Private  186061             10             Widowed   
3       54   Private  140359              4            Divorced   
4       41   Private  264663             10           Separated   
...    ...       ...     ...            ...                 ...   
32556   22   Private  310152             10       Never married   
32557   27   Private  257302             12  Married civ spouse   
32558   40   Private  154374              9  Married civ spouse   
32559   58   Private  151910              9             Widowed   
32560   22   Private  201490              9       Never married   

              occupation   relationship   race     sex  capital.gain  \
0         Prof specialty  Not in family  White  Female             0   
1        Exec managerial  Not in family  White  Female             0   
2         Prof specialty      Unmarried  Black  Female             0   
3      Machine op inspct      Unmarried  White  Female             0   
4         Prof specialty      Own child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective serv  Not in family  White    Male             0   
32557       Tech support           Wife  White  Female             0   
32558  Machine op inspct        Husband  White    Male             0   
32559       Adm clerical      Unmarried  White  Female             0   
32560       Adm clerical      Own child  White    Male             0   

       capital.loss  hours.per.week     native.country  
0              4356              40     Prof specialty  
1              4356              18    Exec managerial  
2              4356              40     Prof specialty  
3              3900              40  Machine op inspct  
4              3900              40     Prof specialty  
...             ...             ...                ...  
32556             0              40    Protective serv  
32557             0              38       Tech support  
32558             0              40  Machine op inspct  
32559             0              40       Adm clerical  
32560             0              20       Adm clerical  

[32561 rows x 13 columns]